"""Add best_seller and new_in_stock

Revision ID: 513e7500e130
Revises: 
Create Date: 2025-07-20 21:01:38.507682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '513e7500e130'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('best_seller', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('new_in_stock', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'new_in_stock')
    op.drop_column('products', 'best_seller')
    # ### end Alembic commands ###
