"""modified product model

Revision ID: 005d353fc698
Revises: ee19fe58242c
Create Date: 2025-08-21 00:33:19.128134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '005d353fc698'
down_revision = 'ee19fe58242c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_colors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_lengths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('length', sa.String(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('color')
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True))

    op.drop_table('product_lengths')
    op.drop_table('product_colors')
    # ### end Alembic commands ###
