"""added order summary column

Revision ID: 105a41349971
Revises: 35565cbc13df
Create Date: 2025-09-17 11:32:10.075792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '105a41349971'
down_revision = '35565cbc13df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_summary', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('order_summary')

    # ### end Alembic commands ###
