"""Add length and color columns to Product

Revision ID: 15d257328bf1
Revises: 2bdcd19f301e
Create Date: 2025-05-13 02:54:03.959194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15d257328bf1'
down_revision = '2bdcd19f301e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('length', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('color')
        batch_op.drop_column('length')

    # ### end Alembic commands ###
