"""modifidied order items

Revision ID: 85ef2acdac67
Revises: 8379ac80e55c
Create Date: 2025-09-02 22:41:52.777684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85ef2acdac67'
down_revision = '8379ac80e55c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_color', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('selected_length', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('selected_length')
        batch_op.drop_column('selected_color')

    # ### end Alembic commands ###
