"""modified the cart items

Revision ID: a12a5127ead3
Revises: 85ef2acdac67
Create Date: 2025-09-03 08:45:06.201681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a12a5127ead3'
down_revision = '85ef2acdac67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_color', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('selected_length', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_column('selected_length')
        batch_op.drop_column('selected_color')

    # ### end Alembic commands ###
